# Generated by Django 4.2.7 on 2023-11-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("user_id", models.UUIDField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.BigIntegerField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("category_id", models.IntegerField()),
                ("created_by", models.EmailField(max_length=254)),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
