# Generated by Django 4.2.7 on 2023-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
