# Generated by Django 4.2.7 on 2023-12-06 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=512)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=512)),
                ('image', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('otp', models.IntegerField(blank=True, default=123456, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
