# Generated by Django 4.2.7 on 2023-11-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_path",
            field=models.TextField(blank=True),
        ),
    ]
