# Generated by Django 4.2.7 on 2023-12-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.TextField(default=''),
        ),
    ]
