# Generated by Django 4.2.7 on 2023-11-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_path',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
